/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JPanal;

import Entities.Product;
import Entities.Store;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayesh
 */
public class Invoice extends javax.swing.JFrame {

   ArrayList<Product> prod= new ArrayList();
   
    public Invoice() {
        initComponents();
        this.setBounds(300,100, 800,550);
        Store.dummyvalues();
    }
    public void resetfield(){
        pr_name.setText("");
        pr_price.setText("");
        pr_cate.setText("");
        pr_quan.setText("");
    }
    
    void setTableValues() {
    if (prod != null) {
        DefaultTableModel model = (DefaultTableModel) sale_list.getModel();
        model.setRowCount(0);
        for (int i = 0; i < prod.size(); i++) {
            Object[] cols = new Object[4];
            cols[0] = prod.get(i).getName();
            cols[1] = prod.get(i).getCategory();
            cols[2] = prod.get(i).getRetail_P();
            cols[3] = prod.get(i).getStock();
            model.addRow(cols);
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cus_amount = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pr_name = new javax.swing.JTextField();
        total_bill = new javax.swing.JTextField();
        pr_price = new javax.swing.JTextField();
        pr_quan = new javax.swing.JTextField();
        pr_cate = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sale_list = new javax.swing.JTable();
        searchbyname = new javax.swing.JTextField();
        bill_b = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton4.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Add");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 153));
        jLabel3.setText("Invoice");

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel1.setText("Tax");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel2.setText("Product detail:");

        cus_amount.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        cus_amount.setForeground(new java.awt.Color(153, 153, 153));
        cus_amount.setText(" GiveAmount");
        cus_amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        cus_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_amountActionPerformed(evt);
            }
        });
        cus_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cus_amountKeyPressed(evt);
            }
        });

        balance.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        balance.setForeground(new java.awt.Color(153, 153, 153));
        balance.setText(" Balance Amount");
        balance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel4.setText("Billing detail:");

        pr_name.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        pr_name.setForeground(new java.awt.Color(153, 153, 153));
        pr_name.setText(" Name");
        pr_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        pr_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pr_nameActionPerformed(evt);
            }
        });

        total_bill.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        total_bill.setForeground(new java.awt.Color(153, 153, 153));
        total_bill.setText(" totalBill");
        total_bill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        total_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_billActionPerformed(evt);
            }
        });

        pr_price.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        pr_price.setForeground(new java.awt.Color(153, 153, 153));
        pr_price.setText(" Price");
        pr_price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        pr_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pr_priceActionPerformed(evt);
            }
        });

        pr_quan.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        pr_quan.setForeground(new java.awt.Color(153, 153, 153));
        pr_quan.setText(" Quantity");
        pr_quan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        pr_quan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pr_quanActionPerformed(evt);
            }
        });

        pr_cate.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        pr_cate.setForeground(new java.awt.Color(153, 153, 153));
        pr_cate.setText(" Category");
        pr_cate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        pr_cate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pr_cateActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 102, 102));
        jButton6.setText("Add");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        sale_list.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        sale_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Category", "Price", "Quantity"
            }
        ));
        sale_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sale_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sale_list);

        searchbyname.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        searchbyname.setForeground(new java.awt.Color(102, 102, 102));
        searchbyname.setText("Search by name");
        searchbyname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        searchbyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbynameActionPerformed(evt);
            }
        });
        searchbyname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchbynameKeyPressed(evt);
            }
        });

        bill_b.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        bill_b.setText("Generate bill");
        bill_b.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        bill_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_bActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(total_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cus_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(pr_name, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(pr_price))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pr_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pr_quan)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 60, Short.MAX_VALUE)))))))
                            .addComponent(searchbyname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(bill_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cus_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(searchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pr_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pr_price, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pr_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pr_quan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton1))
                    .addComponent(bill_b))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.getAccessibleContext().setAccessibleName("Invoice");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cus_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cus_amountActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceActionPerformed

    private void pr_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pr_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pr_nameActionPerformed

    private void total_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_billActionPerformed

    private void pr_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pr_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pr_priceActionPerformed

    private void pr_quanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pr_quanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pr_quanActionPerformed

    private void pr_cateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pr_cateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pr_cateActionPerformed

    private void searchbynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbynameActionPerformed

    private void searchbynameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbynameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
    if (!searchbyname.getText().isEmpty()) {
        Product p = Store.searchByName(searchbyname.getText());
        if (p != null) { // Check if the product is found
            pr_name.setText(p.getName());
            pr_price.setText(String.valueOf(p.getRetail_P()));
            pr_cate.setText(p.getCategory());
        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please fill the required field");
    }
}
    }//GEN-LAST:event_searchbynameKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (!pr_name.getText().isEmpty()
                && !pr_cate.getText().isEmpty() && !pr_price.getText().isEmpty()
                && !pr_quan.getText().isEmpty()) {

            // Create a new product
            Product p = new Product();
            p.setName(pr_name.getText());
            p.setCategory(pr_cate.getText());
            p.setRetail_P(Double.parseDouble(pr_price.getText()));
            p.setStock(Integer.parseInt(pr_quan.getText()));

            // Add the product to the list
            if (prod == null) {
                prod = new ArrayList<>();
            }
            prod.add(p);

            // Update the table values
            setTableValues();

            // Reset the input fields
            resetfield();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void sale_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale_listMouseClicked
        // TODO add your handling code here:
      DefaultTableModel model = (DefaultTableModel) sale_list.getModel();
      int index = sale_list.getSelectedRow();
     String name= model.getValueAt(index, 0).toString();
     int dis=JOptionPane.showConfirmDialog(null, "want to delete product from invoice");
     if(dis==0){
     for(int i=0;i<prod.size();i++){
         if(name.equalsIgnoreCase(prod.get(i).getName())){
             prod.remove(i);
             JOptionPane.showMessageDialog(null,"Product deleted");
             setTableValues();
         } 
     }
      }
    }//GEN-LAST:event_sale_listMouseClicked

    private void bill_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_bActionPerformed
        // TODO add your handling code here:
        
        int total_amount=0;
        for(int i=0;i<prod.size();i++){
            total_amount+=prod.get(i).getRetail_P()*prod.get(i).getStock();
            total_bill.setText(total_amount+"");           
        }
                
    }//GEN-LAST:event_bill_bActionPerformed

    private void cus_amountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cus_amountKeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        if(!total_bill.getText().isEmpty()&&!cus_amount.getText().isEmpty()) {
          int t_amount = Integer.parseInt(total_bill.getText());
          int payment = Integer.parseInt(cus_amount.getText());
          balance.setText(String.valueOf(payment-t_amount));
        }
       } 
    }//GEN-LAST:event_cus_amountKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new LoginPortal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Invoice invoice= new Invoice();
                invoice.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JButton bill_b;
    private javax.swing.JTextField cus_amount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pr_cate;
    private javax.swing.JTextField pr_name;
    private javax.swing.JTextField pr_price;
    private javax.swing.JTextField pr_quan;
    private javax.swing.JTable sale_list;
    private javax.swing.JTextField searchbyname;
    private javax.swing.JTextField total_bill;
    // End of variables declaration//GEN-END:variables
}
